### ISSUE TITLE
tensorflow ./configure failing

### ISSUE THREAD

**Issue by ronilp** [rayglover-ibm/serving-caffe#4]
When I try to run ./configure in tensorflow, I am getting the following output :

```/mnt1/packages/serving-caffe-new/tensorflow /mnt1/packages/serving-caffe-new/tensorflow
Please specify the location of python. [Default is /mnt1/anaconda2/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /mnt1/anaconda2/lib/python2.7/site-packages
  /mnt1/packages/caffe/python
Please input the desired Python library path to use.  Default is [/mnt1/anaconda2/lib/python2.7/site-packages]

Using python library path: /mnt1/anaconda2/lib/python2.7/site-packages

Do you wish to build TensorFlow with OpenCL support? [y/N] No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] 
No GPU support will be enabled for TensorFlow
Configuration finished
..
.........................................................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
...........................................................
ERROR: /private/var/tmp/_bazel_rpancholia/a961ccd01d13d48668361d4e82ff9a77/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /mnt1/packages/serving-caffe-new/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: /private/var/tmp/_bazel_rpancholia/a961ccd01d13d48668361d4e82ff9a77/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /mnt1/packages/serving-caffe-new/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: Evaluation of query "deps(//tensorflow/...)" failed: errors were encountered while computing transitive closure.
```

When I clone tensorflow from https://github.com/tensorflow/tensorflow it works but with this repo, I get this error.
I am getting these errors on Mac OSX 10.12 and CentOS 7.

**Comment by rayglover-ibm** [comment]
Seems to be something to do with android support in Tensorflow/Bazel. Specifically I'd imagine this is something to do with using Bazel on an older version of Tensorflow; what version of Bazel are you using? 

tensorflow/tensorflow/issues/4748 seems similar.

**Comment by ronilp** [comment]
I am using 0.4.4-homebrew version.
Is there some way to bypass these android builds?

**Comment by ChadTaljaardt** [comment]
I'm getting the same issue and I'm using 0.4.4 on Ubuntu 16.10

I'm using Tensorflow 0.12.0

**Comment by ronilp** [comment]
I tried using bazel 0.3.2 and got this error
```
ERROR: /mnt1/serving-caffe/tensorflow/tensorflow/tools/tfprof/BUILD:22:1: no such package '@linenoise//': Error creating symbolic link from /root/.cache/bazel/_bazel_root/2ebba05a0258eb03259dd95438d15311/external/linenoise/BUILD to /mnt1/serving-caffe/tensorflow/linenoise.BUILD: /root/.cache/bazel/_bazel_root/2ebba05a0258eb03259dd95438d15311/external/linenoise/BUILD (No space left on device) and referenced by '//tensorflow/tools/tfprof:tfprof'
```

**Comment by rayglover-ibm** [comment]
I managed to reproduce this `./configure` issue with bazel 0.4.4 on Ubuntu 16.04, and it goes away with tensorflow/tensorflow@63b3fea .

So, this should be fixed in the next update.

**Comment by ChadTaljaardt** [comment]
@rayglover-ibm I made the change local and it has not fixed it for me.

**Comment by rayglover-ibm** [comment]
@ChadTaljaardt what's your output from bazel?

**Comment by ChadTaljaardt** [comment]
@rayglover-ibm 

This used to work before as i have installed this version of tensorflow with this config and it worked. This time its not for some reason.
```
chad@chad-GA-990XA-UD3:~/tensorflow-0.12.0$ ./configure
~/tensorflow-0.12.0 ~/tensorflow-0.12.0
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

Using python library path: /usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..........
ERROR: /home/chad/.cache/bazel/_bazel_chad/205e925a9fa24af878579c0f19b2eb72/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /home/chad/tensorflow-0.12.0/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: /home/chad/.cache/bazel/_bazel_chad/205e925a9fa24af878579c0f19b2eb72/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /home/chad/tensorflow-0.12.0/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: Evaluation of query "deps(//tensorflow/...)" failed: errors were encountered while computing transitive closure.
```

**Comment by rayglover-ibm** [comment]
That's not what the `./configure` output looks like for me `@63b3fea`. It should begin with something like
```
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] n
jemalloc disabled
```

and `git show` should produce
```
commit 63b3fea438b1fc700db38b77ca691e083b63bb5f
Author: Yaroslav Bulatov <yaroslavvb@gmail.com>
Date:   Tue Jan 31 14:36:06 2017 -0800
```

**Comment by ChadTaljaardt** [comment]
@rayglover-ibm  What version of Tensorflow are you using?

**Comment by rayglover-ibm** [comment]
I don't understand the question. 

To be clear, This repository is currently pinned to `dca48e8` of tensorflow which is broken with latest the bazel. manually updating to `63b3fea`  (ie `cd tensorflow && git fetch --all && git checkout 63b3fea` fixes this specific issue.

**Comment by ChadTaljaardt** [comment]
@rayglover-ibm I think it's because we are using different versions. You are compiling from the source I think where I'm using this release: https://github.com/tensorflow/tensorflow/releases/tag/v0.12.0

**Comment by ronilp** [comment]
Using tensorflow 63b3fea works fine for me. Thanks !

**Comment by ronilp** [comment]
Getting this on running sample build after successful tensorflow configure
```
[root@nqa-seeing-docker-1d 10.0.8.221:/mnt1/serving-caffe] bazel build -c opt @caffe//:lib
..
......
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /mnt1/serving-caffe/WORKSPACE:13:6: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'check_version'.
ERROR: /mnt1/serving-caffe/WORKSPACE:14:1: name 'check_version' is not defined.
ERROR: Error evaluating WORKSPACE file.
ERROR: error loading package
```

**Comment by rayglover-ibm** [comment]
@ronilp  The build has been updated for Tensorflow at `63b3fea`. I haven't done any testing on osx (since I don't have a Mac at hand) but hopefully the fixes are sufficient.

**Comment by ronilp** [comment]
Thanks for the fix. I am able to build caffe now.
But when I try to build model server, I get an error. Not sure if the error is related to this fix.
Here is the output
```
[root@nqa-seeing-docker-1d 10.0.8.221:/mnt1/serving-caffe] bazel build -c opt //tensorflow_serving/model_servers:model_server
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /root/.cache/bazel/_bazel_root/0c192fc8d299e86709eb23d934b7ed70/external/org_tensorflow/tensorflow/workspace.bzl:63:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /mnt1/serving-caffe/tensorflow_serving/servables/caffe/BUILD:36:1: target 'pycaffe' is both a rule and a file; please choose another name for the rule.
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/0c192fc8d299e86709eb23d934b7ed70/external/curl/BUILD.bazel:8:1: C++ compilation of rule '@curl//:curl' failed: gcc failed: error executing command /bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 53 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/curl/lib/if2ip.c:47:23: fatal error: stropts.h: No such file or directory
 #  include <stropts.h>
                       ^
compilation terminated.
Target //tensorflow_serving/model_servers:model_server failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.796s, Critical Path: 0.36s
```

**Comment by rayglover-ibm** [comment]
Very odd. I'd be surprised if that error had something to do with tensorflow serving; more likely there is a bug in `tensorflow/third_party/curl.BUILD` in how it is setting `HAVE_STROPTS_H` but it would be challenging for me to figure out why because I'm on Linux.

**Comment by ronilp** [comment]
I am getting this error on CentOS 7

**Comment by ronilp** [comment]
Are you able to build locally?

**Comment by rayglover-ibm** [comment]
Yes, Ubuntu 16.

Does Tensorflow support CentOS?

I'm guessing `stropts.h` doesnt exist on your system?  You could try `touch /usr/include/stropts.h` and see what happens then.

**Comment by ronilp** [comment]
If I normally use tensorflow, it works fine (pip install tensorflow). I have not tried using serve.
